function [stencil_g2f,BCU_g2f,HU,M] = projOp_2_accGlue2Fd1_accFd2Glue1();
%ProjGlue_trad_io1_boG2F0_boF2G0_stencil_4_BC_1_2
%    [STENCIL_G2F,BCU_g2f,HU,M] = ProjGlue_trad_io1_boG2F0_boF2G0_stencil_4_BC_1_2

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    17-Sep-2023 18:23:51

stencil_g2f = [5.0e-1,1.666666666666667e-1,5.0e-1,-1.666666666666667e-1];
if nargout > 1
    BCU_g2f = [1.0,-3.333333333333333e-1];
end
if nargout > 2
    HU = [5.0e-1;1.0];
end
if nargout > 3
    M = [2.0;6.666666666666667e-1];
end
