function F_a = F_a(V,Psi,a,sigma0,V0,tau0)
%F_a
%    F_a = F_a(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:32

t2 = 1.0./V0;
t3 = 1.0./a;
t4 = Psi.*t3;
t5 = exp(t4);
F_a = sigma0.*asinh((V.*t2.*t5)./2.0)-(V.*sigma0.*t2.*t4.*t5.*1.0./sqrt((V.^2.*t2.^2.*exp(t4.*2.0))./4.0+1.0))./2.0;
