function F_a_a = F_a_a(V,Psi,a,sigma0,V0,tau0)
%F_a_a
%    F_a_a = F_a_a(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-May-2026 11:18:53

t2 = Psi.^2;
t3 = V.^2;
t4 = 1.0./V0.^2;
t5 = 1.0./a;
t6 = t5.^3;
t7 = Psi.*t5.*2.0;
t8 = exp(t7);
t9 = (t3.*t4.*t8)./4.0;
t10 = t9+1.0;
F_a_a = (V.*sigma0.*t2.*t6.*1.0./sqrt(t10).*exp(Psi.*t5))./(V0.*2.0)-(V.^3.*1.0./V0.^3.*sigma0.*t2.*t6.*1.0./t10.^(3.0./2.0).*exp(Psi.*t5.*3.0))./8.0;
end
