function F_Psi_a = F_Psi_a(V,Psi,a,sigma0,V0,tau0)
%F_Psi_a
%    F_Psi_a = F_Psi_a(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-May-2026 19:45:26

t2 = V.^2;
t3 = 1.0./V0.^2;
t4 = 1.0./a;
t5 = t4.^2;
t6 = Psi.*t4.*2.0;
t7 = exp(t6);
t8 = (t2.*t3.*t7)./4.0;
t9 = t8+1.0;
F_Psi_a = (Psi.*V.^3.*1.0./V0.^3.*sigma0.*t5.*1.0./t9.^(3.0./2.0).*exp(Psi.*t4.*3.0))./8.0-(Psi.*V.*sigma0.*t5.*1.0./sqrt(t9).*exp(Psi.*t4))./(V0.*2.0);
end
