function F_Psi_Psi = F_Psi_Psi(V,Psi,a,sigma0,V0,tau0)
%F_Psi_Psi
%    F_Psi_Psi = F_Psi_Psi(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-May-2026 19:45:26

t2 = V.^2;
t3 = 1.0./V0.^2;
t4 = 1.0./a;
t5 = Psi.*t4.*2.0;
t6 = exp(t5);
t7 = (t2.*t3.*t6)./4.0;
t8 = t7+1.0;
F_Psi_Psi = V.^3.*1.0./V0.^3.*sigma0.*t4.*1.0./t8.^(3.0./2.0).*exp(Psi.*t4.*3.0).*(-1.0./8.0)+(V.*sigma0.*t4.*1.0./sqrt(t8).*exp(Psi.*t4))./(V0.*2.0);
end
