function F_Psi = F_Psi(V,Psi,a,sigma0,V0,tau0)
%F_Psi
%    F_Psi = F_Psi(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:31

t2 = 1.0./a;
F_Psi = (V.*sigma0.*exp(Psi.*t2).*1.0./sqrt((V.^2.*1.0./V0.^2.*exp(Psi.*t2.*2.0))./4.0+1.0))./(V0.*2.0);
