function F_tau0 = F_tau0(V,Psi,a,sigma0,V0,tau0)
%F_tau0
%    F_tau0 = F_tau0(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:32

F_tau0 = -1.0;
