function F_V0 = F_V0(V,Psi,a,sigma0,V0,tau0)
%F_V0
%    F_V0 = F_V0(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:32

t2 = 1.0./V0.^2;
t3 = 1.0./a;
F_V0 = V.*a.*sigma0.*t2.*exp(Psi.*t3).*1.0./sqrt((V.^2.*t2.*exp(Psi.*t3.*2.0))./4.0+1.0).*(-1.0./2.0);
