function F_V_V = F_V_V(V,Psi,a,sigma0,V0,tau0)
%F_V_V
%    F_V_V = F_V_V(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-May-2026 19:45:25

t2 = 1.0./a;
F_V_V = V.*1.0./V0.^3.*a.*sigma0.*exp(Psi.*t2.*3.0).*1.0./((V.^2.*1.0./V0.^2.*exp(Psi.*t2.*2.0))./4.0+1.0).^(3.0./2.0).*(-1.0./8.0);
end
