function F_V_a = F_V_a(V,Psi,a,sigma0,V0,tau0)
%F_V_a
%    F_V_a = F_V_a(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-May-2026 19:45:26

t2 = V.^2;
t3 = 1.0./V0;
t5 = 1.0./a;
t4 = t3.^2;
t6 = Psi.*t5;
t7 = t6.*2.0;
t8 = exp(t6);
t9 = exp(t7);
t10 = (t2.*t4.*t9)./4.0;
t11 = t10+1.0;
t12 = 1.0./sqrt(t11);
F_V_a = (sigma0.*t3.*t8.*t12)./2.0-(sigma0.*t3.*t6.*t8.*t12)./2.0+(sigma0.*t2.*t3.^3.*t6.*t12.^3.*exp(t6.*3.0))./8.0;
end
