function f = friction_coeff(V,Psi,a,sigma0,V0,tau0)
%FRICTION_COEFF
%    F = FRICTION_COEFF(V,Psi,A,SIGMA0,V0,TAU0)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:31

f = a.*asinh((exp(Psi./a).*abs(V))./(V0.*2.0));
