function f_ss = friction_coeff_steady_state(V,a,b,f0,V0)
%FRICTION_COEFF_STEADY_STATE
%    F_SS = FRICTION_COEFF_STEADY_STATE(V,A,B,F0,V0)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:31

f_ss = f0+log(abs(V)./V0).*(a-b);
