function G_a = G_a(V,Psi,a,b,f0,V0,D_c)
%G_a
%    G_a = G_a(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:33

t2 = abs(V);
t3 = 1.0./V0;
t4 = 1.0./a;
t5 = Psi.*t4;
t6 = exp(t5);
G_a = (t2.*(-asinh((t2.*t3.*t6)./2.0)+log(t2.*t3)+(t2.*t3.*t5.*t6.*1.0./sqrt((t2.^2.*t3.^2.*exp(t5.*2.0))./4.0+1.0))./2.0))./D_c;
