function G_a_a = G_a_a(V,Psi,a,b,f0,V0,D_c)
%G_a_a
%    G_a_a = G_a_a(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-May-2026 11:18:54

t2 = abs(V);
t3 = Psi.^2;
t5 = 1.0./V0.^2;
t6 = 1.0./a;
t4 = t2.^2;
t7 = t6.^3;
t8 = Psi.*t6.*2.0;
t9 = exp(t8);
t10 = (t4.*t5.*t9)./4.0;
t11 = t10+1.0;
G_a_a = (t2.*((1.0./V0.^3.*t2.^3.*t3.*t7.*1.0./t11.^(3.0./2.0).*exp(Psi.*t6.*3.0))./8.0-(t2.*t3.*t7.*1.0./sqrt(t11).*exp(Psi.*t6))./(V0.*2.0)))./D_c;
end
