function G_b = G_b(V,Psi,a,b,f0,V0,D_c)
%G_b
%    G_b = G_b(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:33

t2 = abs(V);
G_b = -(t2.*log(t2./V0))./D_c;
