function G_b_b = G_b_b(V,Psi,a,b,f0,V0,D_c)
%G_b_b
%    G_b_b = G_b_b(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-May-2026 11:18:54

G_b_b = 0.0;
end
