function G_D_c = G_D_c(V,Psi,a,b,f0,V0,D_c)
%G_D_c
%    G_D_c = G_D_c(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:33

t2 = abs(V);
t3 = 1.0./V0;
G_D_c = -1.0./D_c.^2.*t2.*(f0-a.*asinh((t2.*t3.*exp(Psi./a))./2.0)+log(t2.*t3).*(a-b));
