function G_Psi = G_Psi(V,Psi,a,b,f0,V0,D_c)
%G_Psi
%    G_Psi = G_Psi(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:33

t2 = abs(V);
t4 = 1.0./a;
t3 = t2.^2;
G_Psi = (t3.*exp(Psi.*t4).*1.0./sqrt((1.0./V0.^2.*t3.*exp(Psi.*t4.*2.0))./4.0+1.0).*(-1.0./2.0))./(D_c.*V0);
