function G_Psi_Psi = G_Psi_Psi(V,Psi,a,b,f0,V0,D_c)
%G_Psi_Psi
%    G_Psi_Psi = G_Psi_Psi(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-May-2026 19:45:27

t2 = abs(V);
t4 = 1.0./D_c;
t5 = 1.0./V0.^2;
t6 = 1.0./a;
t3 = t2.^2;
t7 = t6.^2;
t8 = Psi.*t6.*2.0;
t9 = exp(t8);
t10 = (t3.*t5.*t9)./4.0;
t11 = t10+1.0;
G_Psi_Psi = (1.0./V0.^3.*t3.^2.*t4.*t7.*1.0./t11.^(3.0./2.0).*exp(Psi.*t6.*3.0))./2.0-1.0./V0.^5.*t3.^3.*t4.*t7.*1.0./t11.^(5.0./2.0).*exp(Psi.*t6.*5.0).*(3.0./3.2e+1)-(t3.*t4.*t7.*1.0./sqrt(t11).*exp(Psi.*t6))./(V0.*2.0);
end
