function G_Psi_a = G_Psi_a(V,Psi,a,b,f0,V0,D_c)
%G_Psi_a
%    G_Psi_a = G_Psi_a(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-May-2026 19:45:27

t2 = abs(V);
t5 = 1.0./D_c;
t6 = 1.0./V0;
t9 = 1.0./a;
t3 = t2.^2;
t7 = t6.^2;
t8 = t6.^3;
t10 = t9.^2;
t11 = t9.^3;
t12 = Psi.*t9;
t4 = t3.^2;
t13 = t12.*2.0;
t14 = t12.*3.0;
t15 = exp(t12);
t16 = exp(t13);
t17 = exp(t14);
t18 = (t3.*t7.*t16)./4.0;
t19 = t18+1.0;
t20 = 1.0./sqrt(t19);
t21 = t20.^3;
G_Psi_a = (t3.*t5.*t6.*t10.*t15.*t20)./2.0-(t4.*t5.*t8.*t10.*t17.*t21)./8.0+Psi.*t3.^3.*t5.*t6.^5.*t11.*t20.^5.*exp(t12.*5.0).*(3.0./3.2e+1)+(Psi.*t3.*t5.*t6.*t11.*t15.*t20)./2.0-(Psi.*t4.*t5.*t8.*t11.*t17.*t21)./2.0;
end
