function G_tau0 = G_tau0(V,Psi,a,b,f0,V0,D_c)
%G_tau0
%    G_tau0 = G_tau0(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:33

G_tau0 = 0.0;
