function G_V = G_V(V,Psi,a,b,f0,V0,D_c)
%G_V
%    G_V = G_V(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:32

t2 = abs(V);
t3 = conj(V);
t6 = 1.0./D_c;
t7 = 1.0./V0;
t8 = 1.0./a;
t9 = -b;
t4 = V.*t3;
t5 = V+t3;
t10 = Psi.*t8;
t11 = a+t9;
t12 = exp(t10);
t13 = 1.0./sqrt(t4);
G_V = t2.*t6.*((t5.*t11.*t13)./(t2.*2.0)-(a.*t5.*t7.*t12.*t13.*1.0./sqrt((t2.^2.*t7.^2.*exp(t10.*2.0))./4.0+1.0))./4.0)+(t5.*t6.*t13.*(f0+t11.*log(t2.*t7)-a.*asinh((t2.*t7.*t12)./2.0)))./2.0;
