function G_V0 = G_V0(V,Psi,a,b,f0,V0,D_c)
%G_V0
%    G_V0 = G_V0(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2023 12:55:33

t2 = abs(V);
t3 = 1.0./V0.^2;
t4 = 1.0./a;
G_V0 = -(t2.*((a-b)./V0-(a.*t2.*t3.*exp(Psi.*t4).*1.0./sqrt((t2.^2.*t3.*exp(Psi.*t4.*2.0))./4.0+1.0))./2.0))./D_c;
