function G_V_Psi = G_V_Psi(V,Psi,a,b,f0,V0,D_c)
%G_V_Psi
%    G_V_Psi = G_V_Psi(V,Psi,A,B,F0,V0,D_c)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-May-2026 19:45:27

t2 = abs(V);
t3 = conj(V);
t7 = 1.0./D_c;
t9 = 1.0./V0;
t12 = 1.0./a;
t4 = t2.^2;
t5 = V.*t3;
t6 = V+t3;
t10 = t9.^2;
t11 = t9.^3;
t14 = Psi.*t12;
t15 = t6.^2;
t16 = t14.*2.0;
t17 = t14.*3.0;
t18 = exp(t14);
t21 = 1.0./sqrt(t5);
t19 = exp(t16);
t20 = exp(t17);
t22 = t21.^3;
t23 = (t4.*t10.*t19)./4.0;
t24 = t23+1.0;
t25 = 1.0./sqrt(t24);
t26 = t25.^3;
G_V_Psi = -t2.*t7.*((t9.*t18.*t21.*t25)./2.0-(t4.*t11.*t20.*t21.*t26)./8.0-(t9.*t15.*t18.*t22.*t25)./8.0+(t4.*t11.*t15.*t20.*t22.*t26)./3.2e+1+t2.^3.*t9.^5.*t15.*t21.^2.*t25.^5.*exp(t14.*5.0).*(3.0./1.28e+2)-t2.*t11.*t15.*t20.*t21.^2.*t26.*(3.0./3.2e+1))-t6.*t7.*t21.*((t6.*t9.*t18.*t21.*t25)./4.0-(t4.*t6.*t11.*t20.*t21.*t26)./1.6e+1)-(t2.*t7.*t9.*t18.*t21.*t25)./2.0+(t2.*t7.*t9.*t15.*t18.*t22.*t25)./8.0;
end
